In [4]:
import torch

import numpy as np

In [5]:
data = [[1,2] , [3,4]]
x_data = torch.tensor(data)

In [6]:
# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor :\n {x_ones}")

x_rand = torch.rand_like(x_data , dtype = torch.float)
print(f"random tensor : \n {x_rand}")


ones tensor :
 tensor([[1, 1],
        [1, 1]])
random tensor : 
 tensor([[0.5725, 0.5850],
        [0.8308, 0.2695]])


In [8]:
shape = (2 ,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7160, 0.9967, 0.1308],
        [0.1997, 0.7458, 0.4496]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
tensor = torch.rand(3 , 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [11]:
tensor = torch.ones(4,4)
tensor[2,1] = 3
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 3., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
tensor = torch.ones(4,4)
tensor[:,2] = 3
print(tensor)

tensor([[1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.]])


In [13]:
t1 = torch.cat([tensor , tensor , tensor] , dim = 1)
print(t1 , len(t1))

tensor([[1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.]]) 4


In [14]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


tensor.mul(tensor) 
 tensor([[1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.]])


In [15]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax: T is transpose
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]]) 

tensor @ tensor.T 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])


In [16]:
print(tensor , "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.]]) 

tensor([[6., 6., 8., 6.],
        [6., 6., 8., 6.],
        [6., 6., 8., 6.],
        [6., 6., 8., 6.]])


In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [19]:
n = np.ones(5)
t = torch.from_numpy(n)

In [20]:
np.add(n , 1 , out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# **Autograd**

In [21]:
import torch
from torchvision.models import resnet18 , ResNet18_Weights
model = resnet18(weights = ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1 ,1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:00<00:00, 137MB/s]


In [22]:
print(labels)
len(labels) #1
len(labels[0]) #1000

tensor([[2.0245e-01, 6.7319e-01, 1.3741e-01, 4.2751e-01, 5.9627e-01, 4.5533e-02,
         9.7758e-01, 5.9513e-02, 1.0617e-01, 6.6084e-02, 5.4233e-01, 1.1557e-01,
         8.2680e-01, 6.8204e-01, 7.6074e-01, 7.4207e-01, 8.1979e-02, 7.7461e-01,
         4.6825e-01, 1.1403e-01, 8.7412e-01, 3.4054e-01, 4.7242e-01, 2.1007e-01,
         5.2999e-01, 3.2052e-01, 1.7533e-01, 5.8838e-01, 7.2192e-01, 9.7162e-01,
         4.8838e-01, 3.5087e-01, 2.1167e-03, 9.6464e-02, 2.9509e-01, 8.7844e-01,
         9.9559e-01, 2.6667e-01, 4.6259e-01, 5.6133e-02, 9.0168e-01, 6.8374e-02,
         7.4255e-01, 1.9696e-02, 5.3496e-01, 6.4860e-02, 9.1338e-01, 7.3482e-01,
         9.6438e-02, 9.0360e-01, 6.0113e-01, 3.7153e-01, 8.1313e-01, 4.6972e-01,
         1.8635e-02, 9.1947e-01, 3.4722e-01, 2.1075e-01, 5.5857e-01, 9.3309e-01,
         5.1029e-02, 1.2532e-01, 2.8243e-01, 5.1902e-01, 7.7018e-01, 1.9650e-01,
         2.1959e-01, 3.5063e-02, 4.7503e-01, 4.2453e-01, 2.4230e-02, 9.7037e-01,
         2.5256e-01, 8.7687e

1000

In [23]:
prediction = model(data)
print(prediction)

tensor([[-7.4265e-01, -3.3953e-01, -6.5945e-01, -1.4132e+00, -7.8391e-01,
         -2.1758e-01, -3.8028e-01,  5.3898e-01,  4.7793e-01, -7.5455e-01,
         -9.3404e-01, -7.2771e-01, -4.0911e-01, -8.5013e-01, -7.9936e-01,
         -6.4688e-01, -1.0167e+00, -4.6393e-01, -4.3042e-01, -6.2253e-01,
         -1.3343e+00, -7.7558e-01, -1.6262e+00,  1.0183e-01, -1.1810e+00,
         -1.3251e+00, -8.2822e-01, -1.2837e+00, -8.5036e-01, -2.0523e-01,
         -6.6480e-01, -5.8598e-01, -3.1761e-01, -2.9411e-01,  1.7552e-02,
         -2.0398e-01,  7.5875e-01, -4.5070e-01, -3.1216e-01, -1.3415e-01,
         -7.7151e-01, -8.0456e-01, -9.5807e-01, -3.6950e-01, -5.5797e-01,
         -1.6171e-01, -6.6280e-01, -5.2301e-01, -1.1269e+00, -9.3450e-01,
         -4.1703e-01,  4.3953e-01,  4.4657e-02, -5.9913e-01,  7.9705e-02,
         -7.1445e-01, -2.5665e-01, -1.1776e+00, -3.7633e-01, -4.6092e-02,
          1.1264e+00,  2.9282e-01,  3.1746e-01,  3.9471e-01, -3.3313e-01,
          2.2611e-01, -1.1921e-01, -4.

In [24]:
loss = (prediction - labels).sum()
loss.backward()

In [25]:
optim = torch.optim.SGD(model.parameters() , lr = 1e-2 , momentum = 0.9)

In [26]:
optim.step()

# **Neural Networks**

In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [28]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1 , 6 ,5)
    self.conv2 = nn.Conv2d(6 , 16 , 5)
    self.fc1 = nn.Linear(16*5*5 , 120)
    self.fc2 = nn.Linear(120 , 84)
    self.fc3 = nn.Linear(84 , 10)

  def forward(self, input):
    c1 = F.relu(self.conv1(input))
    s2 = F.max_pool2d(c1,(2,2))
    c3 = F.relu(self.conv2(s2))
    s4 = F.max_pool2d(c3 , 2)
    s4 = torch.flatten(s4 , 1)
    f5 = F.relu(self.fc1(s4))
    f6 = F.relu(self.fc2(f5))
    output = self.fc3(f6)
    return output


net = Net()

print(net)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [29]:
params = list(net.parameters())
print(len(params))

for para in params:
  print(para.size() )

10
torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([16, 6, 5, 5])
torch.Size([16])
torch.Size([120, 400])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [30]:
input = torch.randn(1 , 1 , 32 , 32)
out = net(input)
print(out)

tensor([[ 0.1359, -0.0019,  0.0452, -0.1208,  0.0151,  0.0382, -0.0956,  0.1719,
          0.0582, -0.0006]], grad_fn=<AddmmBackward0>)


In [31]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [32]:
output = net(input)
target = torch.randn(10)
target = target.view(1 ,-1)
criterion = nn.MSELoss()

loss = criterion(output , target)
print(loss)

tensor(1.4257, grad_fn=<MseLossBackward0>)


In [33]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

# **Backprop**

In [34]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([-0.0097,  0.0038, -0.0111, -0.0006, -0.0031,  0.0078])


# **Update the weights**
weight = weight - learning_rate * gradient

# ***Manual way***

In [35]:
learning_rate = 0.01
for f in net.parameters():
  with torch.no_grad():
    f -= f.grad*learning_rate

# Built in

In [36]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters() , lr = 0.01)

optimizer.zero_grad()
output= net(input)
loss = criterion(output , target)
loss.backward()
optimizer.step()



# **Training Classifier**

In [37]:
import torch
import torchvision
from torchvision.transforms import v2

In [38]:
transform = v2.Compose([v2.ToImage() ,
                        v2.ToDtype(torch.float32 , scale = True),
                        v2.Normalize((0.5 , 0.5 , 0.5) , (0.5 , 0.5 , 0.5))])
batch_size = 4
trainset = torchvision.datasets.CIFAR10(root = './data' , train = True , download = True , transform = transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

100%|██████████| 170M/170M [34:14<00:00, 83.0kB/s]


In [39]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(3 , 6 , 5)
    self.conv2 = nn.Conv2d(6 , 16 ,5)
    self.pool = nn.MaxPool2d(2,2)
    self.fc1 = nn.Linear(16*5*5 , 120)
    self.fc2 = nn.Linear(120 , 84)
    self.fc3 = nn.Linear(84 , 10)

  def forward(self , x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = torch.flatten(x,1)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

net = Net()


In [40]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters() , lr = 0.001 , momentum = 0.9)


In [41]:
for epoch in range(2):
  running_loss = 0.0
  for i , data in enumerate(trainloader , 0):
    inputs , labels = data
    optimizer.zero_grad()
    outputs = net(inputs)
    loss  = criterion (outputs , labels)
    loss.backward()
    optimizer.step()

    running_loss += loss.item()
    if i%2000 == 1999:
       print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
       running_loss = 0.0




print('FInished Training')

[1,  2000] loss: 2.178
[1,  4000] loss: 1.845
[1,  6000] loss: 1.658
[1,  8000] loss: 1.590
[1, 10000] loss: 1.528
[1, 12000] loss: 1.498
[2,  2000] loss: 1.422
[2,  4000] loss: 1.398
[2,  6000] loss: 1.363
[2,  8000] loss: 1.340
[2, 10000] loss: 1.299
[2, 12000] loss: 1.299
FInished Training


In [ ]:
PATH = './cifar_net.pt'
torch.save(net.state_dict() , PATH)

In [ ]:
def imshow(img):
    img = img / 2 + 0.5
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

In [ ]:
dataiter = iter(testloader)
images , labels = next(dataiter)

imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join(f'{classes[labels[j]]:5s}' for j in range(4)))

In [ ]:
net = Net()
net.load_satet_dict(torch.load(PATH , weights_only = True))

In [ ]:
output = net(images)


In [ ]:
_, predicted = torch.max(outputs, 1)

print('Predicted: ', ' '.join(f'{classes[predicted[j]]:5s}'
                              for j in range(4)))

In [ ]:
correct = 0
total = 0
with torch.no_grad():
  for data in testloader:
    images , labels = data

    outputs = net(images)
    _, predicted = torch.max(output , 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()


print(f'Accuracy of the network on the 10000 test images: {100 * correct // total} %')


In [ ]:
# prepare to count predictions for each class
correct_pred = {classname: 0 for classname in classes}
total_pred = {classname: 0 for classname in classes}

# again no gradients needed
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predictions = torch.max(outputs, 1)
        # collect the correct predictions for each class
        for label, prediction in zip(labels, predictions):
            if label == prediction:
                correct_pred[classes[label]] += 1
            total_pred[classes[label]] += 1


# print accuracy for each class
for classname, correct_count in correct_pred.items():
    accuracy = 100 * float(correct_count) / total_pred[classname]
    print(f'Accuracy for class: {classname:5s} is {accuracy:.1f} %')