In [ ]:
import torch

import numpy as np

In [ ]:
data = [[1,2] , [3,4]]
x_data = torch.tensor(data)

In [ ]:
# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor :\n {x_ones}")

x_rand = torch.rand_like(x_data , dtype = torch.float)
print(f"random tensor : \n {x_rand}")


ones tensor :
 tensor([[1, 1],
        [1, 1]])
random tensor : 
 tensor([[0.1805, 0.3401],
        [0.5779, 0.7880]])


In [ ]:
shape = (2 ,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3918, 0.4748, 0.4686],
        [0.8126, 0.5786, 0.5180]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3 , 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [ ]:
tensor = torch.ones(4,4)
tensor[2,1] = 3
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 3., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
tensor = torch.ones(4,4)
tensor[:,2] = 3
print(tensor)

tensor([[1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.]])


In [ ]:
t1 = torch.cat([tensor , tensor , tensor] , dim = 1)
print(t1 , len(t1))

tensor([[1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.]]) 4


In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


tensor.mul(tensor) 
 tensor([[1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.]])


In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax: T is transpose
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]]) 

tensor @ tensor.T 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])


In [ ]:
print(tensor , "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.]]) 

tensor([[6., 6., 8., 6.],
        [6., 6., 8., 6.],
        [6., 6., 8., 6.],
        [6., 6., 8., 6.]])


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n , 1 , out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# **Autograd**

In [ ]:
import torch
from torchvision.models import resnet18 , ResNet18_Weights
model = resnet18(weights = ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1 ,1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:00<00:00, 200MB/s]


In [ ]:
print(labels)
len(labels) #1
len(labels[0]) #1000

tensor([[2.8676e-01, 7.9672e-01, 1.7398e-01, 3.7221e-01, 4.8624e-01, 6.5031e-01,
         9.7564e-01, 4.8697e-01, 5.4355e-02, 4.2233e-01, 7.5843e-01, 9.6397e-01,
         4.9302e-01, 1.8321e-01, 3.5173e-01, 3.5032e-01, 6.8761e-01, 7.7913e-02,
         5.6449e-01, 3.6532e-01, 9.7385e-01, 3.4024e-01, 5.8030e-01, 3.6752e-01,
         8.9676e-01, 2.0572e-01, 8.8715e-01, 7.9554e-01, 1.5381e-01, 7.3957e-01,
         7.0708e-02, 3.8860e-01, 2.5130e-01, 1.3302e-01, 6.9932e-01, 5.8959e-01,
         2.9857e-01, 7.0979e-01, 4.8994e-01, 2.7701e-02, 5.8728e-01, 9.1457e-01,
         6.6068e-03, 5.6268e-01, 8.1409e-02, 2.8253e-01, 3.0516e-01, 5.4324e-02,
         5.8159e-01, 5.2637e-01, 4.7510e-01, 3.3484e-01, 1.5134e-01, 7.2826e-01,
         6.3825e-01, 6.4874e-01, 7.2800e-01, 3.4293e-01, 2.3416e-01, 1.0615e-01,
         8.5358e-01, 5.9747e-01, 6.9050e-01, 9.3719e-02, 7.9798e-01, 9.4112e-01,
         9.2261e-01, 3.8998e-01, 8.1824e-01, 9.8815e-01, 9.5134e-01, 7.3988e-01,
         9.2567e-01, 2.9441e

1000

In [ ]:
prediction = model(data)
print(prediction)

tensor([[-7.5952e-01, -4.7530e-01, -5.1233e-01, -1.7060e+00, -8.1287e-01,
         -2.6642e-01, -4.7427e-01,  6.2993e-01,  4.9256e-01, -7.7191e-01,
         -8.5928e-01, -1.1391e+00,  4.6111e-02, -7.9492e-01, -7.8879e-01,
         -6.0282e-01, -7.1268e-01, -7.6410e-02, -6.2814e-01, -5.9733e-01,
         -1.2984e+00, -4.0562e-01, -1.1381e+00,  5.6308e-01, -7.9303e-01,
         -1.5767e+00, -1.1587e+00, -1.5169e+00, -1.2031e+00, -6.0702e-01,
         -7.2917e-01, -1.0014e+00, -4.3165e-01, -3.8209e-01, -2.8419e-01,
         -2.9533e-01,  9.8431e-01, -6.1635e-01, -2.0349e-01,  2.1555e-01,
         -8.3217e-01, -4.6009e-01, -8.9689e-01, -2.7984e-03, -4.7666e-01,
         -2.2856e-01, -6.6780e-01, -2.5631e-01, -1.0238e+00, -8.7976e-01,
         -1.2844e-01,  5.2930e-01, -4.0686e-01, -7.5683e-01,  9.3607e-02,
         -1.0316e+00, -2.2095e-02, -1.1903e+00, -2.5269e-01, -2.2970e-01,
          8.2920e-01,  3.0585e-01,  5.9514e-02,  3.5983e-01, -5.2660e-01,
         -3.1263e-01, -5.3410e-02, -7.

In [ ]:
loss = (prediction - labels).sum()
loss.backward()

In [ ]:
optim = torch.optim.SGD(model.parameters() , lr = 1e-2 , momentum = 0.9)

In [ ]:
optim.step()

# **Neural Networks**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [ ]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1 , 6 ,5)
    self.conv2 = nn.Conv2d(6 , 16 , 5)
    self.fc1 = nn.Linear(16*5*5 , 120)
    self.fc2 = nn.Linear(120 , 84)
    self.fc3 = nn.Linear(84 , 10)

  def forward(self, input):
    c1 = F.relu(self.conv1(input))
    s2 = F.max_pool2d(c1,(2,2))
    c3 = F.relu(self.conv2(s2))
    s4 = F.max_pool2d(c3 , 2)
    s4 = torch.flatten(s4 , 1)
    f5 = F.relu(self.fc1(s4))
    f6 = F.relu(self.fc2(f5))
    output = self.fc3(f6)
    return output


net = Net()

print(net)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
