In [39]:
import torch

import numpy as np

In [40]:
data = [[1,2] , [3,4]]
x_data = torch.tensor(data)

In [41]:
# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [42]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor :\n {x_ones}")

x_rand = torch.rand_like(x_data , dtype = torch.float)
print(f"random tensor : \n {x_rand}")


ones tensor :
 tensor([[1, 1],
        [1, 1]])
random tensor : 
 tensor([[0.5623, 0.3681],
        [0.4125, 0.5018]])


In [43]:
shape = (2 ,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0721, 0.2189, 0.3858],
        [0.0890, 0.7737, 0.8563]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [44]:
tensor = torch.rand(3 , 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [45]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [46]:
tensor = torch.ones(4,4)
tensor[2,1] = 3
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 3., 1., 1.],
        [1., 1., 1., 1.]])


In [47]:
tensor = torch.ones(4,4)
tensor[:,2] = 3
print(tensor)

tensor([[1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.]])


In [48]:
t1 = torch.cat([tensor , tensor , tensor] , dim = 1)
print(t1 , len(t1))

tensor([[1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.],
        [1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1.]]) 4


In [49]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


tensor.mul(tensor) 
 tensor([[1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.],
        [1., 1., 9., 1.]])


In [50]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax: T is transpose
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]]) 

tensor @ tensor.T 
 tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])


In [51]:
print(tensor , "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.],
        [1., 1., 3., 1.]]) 

tensor([[6., 6., 8., 6.],
        [6., 6., 8., 6.],
        [6., 6., 8., 6.],
        [6., 6., 8., 6.]])


In [52]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [53]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [54]:
n = np.ones(5)
t = torch.from_numpy(n)

In [55]:
np.add(n , 1 , out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# **Autograd**

In [56]:
import torch
from torchvision.models import resnet18 , ResNet18_Weights
model = resnet18(weights = ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1 ,1000)

In [57]:
print(labels)
len(labels) #1
len(labels[0]) #1000

tensor([[6.7084e-01, 3.4228e-01, 2.2043e-02, 5.4412e-02, 6.4206e-01, 5.7136e-02,
         3.4504e-01, 3.4407e-01, 3.6439e-02, 2.6627e-01, 4.3698e-01, 2.5783e-01,
         3.5118e-01, 2.8387e-01, 1.2889e-01, 5.1022e-01, 6.9848e-01, 6.4567e-01,
         7.7621e-02, 6.4077e-01, 9.0684e-01, 1.6107e-01, 5.5441e-01, 5.8877e-01,
         4.2083e-01, 4.1357e-01, 9.0176e-01, 5.0765e-01, 9.2132e-01, 6.8092e-01,
         5.8114e-02, 5.5754e-01, 4.7233e-01, 2.7129e-01, 1.2168e-01, 3.1571e-01,
         3.9541e-01, 9.2432e-03, 4.0190e-01, 7.8376e-01, 3.4192e-01, 5.6414e-01,
         6.3218e-01, 4.4332e-02, 3.0901e-01, 7.8059e-01, 2.7886e-01, 8.3565e-01,
         8.7455e-02, 9.3267e-01, 8.6752e-01, 5.5467e-01, 2.5126e-01, 4.0196e-01,
         9.4712e-04, 2.5033e-02, 2.0873e-01, 6.2878e-01, 4.7221e-01, 8.4535e-01,
         3.1576e-01, 8.9152e-01, 9.4628e-02, 3.3947e-01, 5.3653e-01, 4.6095e-01,
         3.6687e-01, 7.6798e-01, 5.8769e-01, 9.4069e-03, 3.3634e-01, 9.1940e-01,
         3.2721e-02, 2.9138e

1000

In [58]:
prediction = model(data)
print(prediction)

tensor([[-6.2675e-01, -4.8100e-01, -8.1338e-01, -1.7562e+00, -8.4368e-01,
         -4.3527e-02, -3.9568e-01,  4.1827e-01,  2.5169e-01, -8.7285e-01,
         -1.0414e+00, -7.4065e-01, -3.0583e-01, -1.1433e+00, -1.1663e+00,
         -6.8802e-01, -8.5444e-01, -3.2278e-01, -7.1813e-01, -7.0192e-01,
         -1.8141e+00, -9.0358e-01, -1.4229e+00,  1.2259e-01, -1.1031e+00,
         -1.0847e+00, -5.6868e-01, -1.1357e+00, -8.3636e-01, -1.6350e-01,
         -7.9218e-01, -5.3671e-01, -2.8687e-01, -2.7884e-01, -3.9464e-01,
         -3.7460e-01,  7.2077e-01, -5.1408e-01, -1.9455e-02,  3.6962e-01,
         -5.5718e-01, -7.4302e-01, -1.0207e+00, -2.1662e-01, -4.9106e-01,
         -3.0792e-01, -6.2887e-01, -6.0286e-02, -1.2119e+00, -1.0526e+00,
         -5.5126e-01,  2.9647e-01, -3.9721e-01, -6.5617e-01, -3.0720e-01,
         -9.7573e-01, -3.0534e-01, -1.5678e+00, -5.2532e-01, -3.7721e-01,
          9.3244e-01,  2.6719e-01, -7.6327e-02,  7.7939e-02, -4.8292e-01,
         -1.4494e-01, -9.8094e-02, -3.

In [59]:
loss = (prediction - labels).sum()
loss.backward()

In [60]:
optim = torch.optim.SGD(model.parameters() , lr = 1e-2 , momentum = 0.9)

In [61]:
optim.step()

# **Neural Networks**

In [62]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [63]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1 , 6 ,5)
    self.conv2 = nn.Conv2d(6 , 16 , 5)
    self.fc1 = nn.Linear(16*5*5 , 120)
    self.fc2 = nn.Linear(120 , 84)
    self.fc3 = nn.Linear(84 , 10)

  def forward(self, input):
    c1 = F.relu(self.conv1(input))
    s2 = F.max_pool2d(c1,(2,2))
    c3 = F.relu(self.conv2(s2))
    s4 = F.max_pool2d(c3 , 2)
    s4 = torch.flatten(s4 , 1)
    f5 = F.relu(self.fc1(s4))
    f6 = F.relu(self.fc2(f5))
    output = self.fc3(f6)
    return output


net = Net()

print(net)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [64]:
params = list(net.parameters())
print(len(params))

for para in params:
  print(para.size() )

10
torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([16, 6, 5, 5])
torch.Size([16])
torch.Size([120, 400])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [65]:
input = torch.randn(1 , 1 , 32 , 32)
out = net(input)
print(out)

tensor([[ 0.0280,  0.1045,  0.0152,  0.0166, -0.1021,  0.0858, -0.0950, -0.0615,
         -0.0517, -0.0707]], grad_fn=<AddmmBackward0>)


In [66]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [67]:
output = net(input)
target = torch.randn(10)
target = target.view(1 ,-1)
criterion = nn.MSELoss()

loss = criterion(output , target)
print(loss)

tensor(1.0310, grad_fn=<MseLossBackward0>)


In [68]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

# **Backprop**

In [69]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([ 0.0202, -0.0020, -0.0140, -0.0012,  0.0011,  0.0140])


# **Update the weights**
weight = weight - learning_rate * gradient

# ***Manual way***

In [70]:
learning_rate = 0.01
for f in net.parameters():
  with torch.no_grad():
    f -= f.grad*learning_rate

# Built in

In [71]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters() , lr = 0.01)

optimizer.zero_grad()
output= net(input)
loss = criterion(output , target)
loss.backward()
optimizer.step()



# **Training Classifier**

In [72]:
import torch
import torchvision
from torchvision.transforms import v2

In [73]:
transform = v2.Compose([v2.ToImage() ,
                        v2.ToDtype(torch.float32 , scale = True),
                        v2.Normalize((0.5 , 0.5 , 0.5) , (0.5 , 0.5 , 0.5))])
batch_size = 4
trainset = torchvision.datasets.CIFAR10(root = './data' , train = True , download = True , transform = transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [81]:
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(3 , 6 , 5)
    self.conv2 = nn.Conv2d(6 , 16 ,5)
    self.pool = nn.MaxPool2d(2,2)
    self.fc1 = nn.Linear(16*5*5 , 120)
    self.fc2 = nn.Linear(120 , 84)
    self.fc3 = nn.Linear(84 , 10)

  def forward(self , x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = torch.flatten(x,1)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

net = Net()


In [84]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters() , lr = 0.001 , momentum = 0.9)


In [86]:
for epoch in range(2):
  running_loss = 0.0
  for i , data in enumerate(trainloader , 0):
    inputs , labels = data
    optimizer.zero_grad()
    outputs = net(inputs)
    loss  = criterion (outputs , labels)
    loss.backward()
    optimizer.step()

    running_loss += loss.item()
    if i%2000 == 1999:
       print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
       running_loss = 0.0




print('FInished Training')

[1,  2000] loss: 1.848
[1,  4000] loss: 1.654
[1,  6000] loss: 1.586
[1,  8000] loss: 1.527
[1, 10000] loss: 1.492
[1, 12000] loss: 1.455
[2,  2000] loss: 1.371
[2,  4000] loss: 1.349
[2,  6000] loss: 1.344
[2,  8000] loss: 1.311
[2, 10000] loss: 1.300
[2, 12000] loss: 1.273
FInished Training


In [87]:
PATH = './cifar_net.pt'
torch.save(net.state_dict() , PATH)

In [88]:
dataiter = iter(testloader)
images , labels = next(dataiter)

imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join(f'{classes[labels[j]]:5s}' for j in range(4)))

NameError: name 'imshow' is not defined

In [ ]:
net = Net()
net.load_satet_dict(torch.load(PATH , weights_only = True))

In [ ]:
output = net(images)


In [ ]:
_, predicted = torch.max(outputs, 1)

print('Predicted: ', ' '.join(f'{classes[predicted[j]]:5s}'
                              for j in range(4)))

In [ ]:
correct = 0
total = 0
with torch.no_grad():
  for data in testloader:
    images , labels = data

    outputs = net(images)
    _, predicted = torch.max(output , 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()


print(f'Accuracy of the network on the 10000 test images: {100 * correct // total} %')


In [ ]:
# prepare to count predictions for each class
correct_pred = {classname: 0 for classname in classes}
total_pred = {classname: 0 for classname in classes}

# again no gradients needed
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predictions = torch.max(outputs, 1)
        # collect the correct predictions for each class
        for label, prediction in zip(labels, predictions):
            if label == prediction:
                correct_pred[classes[label]] += 1
            total_pred[classes[label]] += 1


# print accuracy for each class
for classname, correct_count in correct_pred.items():
    accuracy = 100 * float(correct_count) / total_pred[classname]
    print(f'Accuracy for class: {classname:5s} is {accuracy:.1f} %')